# Production Configuration for CUB-200-2011 Training
# Optimized for full model training on cluster/GPU

data:
  cub_root: "data/CUB_200_2011"
  output_dir: "outputs"

training:
  batch_size: 32
  num_epochs: 150      # Extended training for better convergence
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 4
  
  # Learning rate scheduling
  scheduler: "StepLR"
  step_size: 30
  gamma: 0.1
  
  # Early stopping
  patience: 20
  min_delta: 0.001

model:
  backbone: "resnet50"
  num_attributes: 312
  dropout_rate: 0.5
  
  # Model optimization
  pretrained: true
  freeze_backbone: false

calibration:
  split: "val"
  metric: "f1"

shortlisting:
  k_candidates: 5
  min_similarity: 0.1
  use_ground_truth_centroids: false

llm:
  model_name: "llama3"
  temperature: 0.7
  max_tokens: 500

evaluation:
  test_split: "test"
  k_values: [1, 3, 5, 10, 15, 20]

outputs:
  dataset_manifest: "outputs/dataset_manifest.csv"
  attribute_prevalence: "outputs/attribute_prevalence.json"
  model_weights: "outputs/best_model.pth"
  thresholds: "outputs/calibrated_thresholds.json"
  centroids: "outputs/species_centroids.json"
  attribute_mapping: "outputs/attribute_mapping.json"
  results: "outputs/pipeline_results.json"

wandb:
  enabled: true
  project: "cub-bird-identification"
  run_name: "resnet50-full-training"
