# Quick Configuration for CUB-200 Bird Attribute Training
data:
  cub_root: "/Users/smileeee/Documents/Image Scan/data/CUB_200_2011"  # Update this path
  output_dir: "/Users/smileeee/Documents/Image Scan/outputs"

# Model configuration
model:
  architecture: "resnet50"
  num_attributes: 312
  dropout_rate: 0.3
  use_pretrained: true

# Training configuration
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 5  # Quick training for demo
  weight_decay: 0.0001
  device: "cuda"
  num_workers: 4

# Calibration
calibration:
  split: "val"
  metric: "f1"

# Candidate shortlisting
shortlisting:
  k_candidates: 5
  min_similarity: 0.0
  use_ground_truth_centroids: false

# LLM configuration
llm:
  model_name: "gpt-3.5-turbo"
  temperature: 0.3
  max_tokens: 200

# Evaluation
evaluation:
  test_split: "test"
  k_values: [1, 3, 5, 10]

# Output paths
outputs:
  dataset_manifest: "/Users/smileeee/Documents/Image Scan/outputs/dataset_manifest.csv"
  attribute_prevalence: "/Users/smileeee/Documents/Image Scan/outputs/attribute_prevalence.json"
  model_weights: "/Users/smileeee/Documents/Image Scan/outputs/best_model.pth"
  thresholds: "/Users/smileeee/Documents/Image Scan/outputs/calibrated_thresholds.json"
  centroids: "/Users/smileeee/Documents/Image Scan/outputs/species_centroids.pkl"
  attribute_mapping: "/Users/smileeee/Documents/Image Scan/outputs/attribute_mapping.json"
  results: "/Users/smileeee/Documents/Image Scan/outputs/evaluation_results.json"

# Optional: Weights & Biases logging
wandb:
  enabled: false
  project: "cub-bird-identification"
